### ISSUE TITLE
Thumbnails to gimp resources

### ISSUE THREAD

**Issue by americogobbo** [Deevad/gnome-kra-ora-thumbnailer#2]
Hi David,
is possible to use this schema to do thumbnails of gimp resources on gnome?

**Comment by Deevad** [comment]
Hi Americo, 
This thumbnailer can only extract a *.png thumbnail ( created by the application at the moment of saving ) inside an archive. That's how *.kra and *.ora files are designed ( open document, as open office files ). 
I don't think brush tip, gradients, palette ( gimp resources ) use this format.
